# config.py
TOTAL_SUPPLY = 1_000_000_000
TOKENS_PER_MINT = 2_000
TOTAL_MINTS = 500_000
DEV_WALLET_BALANCE = 9_098_199
CIRCULATING_SUPPLY = TOTAL_SUPPLY - DEV_WALLET_BALANCE

# Token Metadata
TOKEN_NAME = "FOMOON"
TOKEN_TICKER = "FOMOON"
DESCRIPTION = "FOMOON is a community-driven token built on the Kaspa KRC-20 ecosystem."
WEBSITE = "https://fomoon.com"
